'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManualEntry

    '''<summary>
    '''form1 control.
    '''</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtDate control.
    '''</summary>
    Protected WithEvents txtDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnReload control.
    '''</summary>
    Protected WithEvents btnReload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave control.
    '''</summary>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveAndExport control.
    '''</summary>
    Protected WithEvents btnSaveAndExport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStatus control.
    '''</summary>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''phFields control.
    '''</summary>
    Protected WithEvents phFields As Global.System.Web.UI.WebControls.PlaceHolder
End Class
